@echo off
echo Stopping WMI Service...
net stop winmgmt /y
echo Killing WMI Provider Host...
taskkill /f /im WmiPrvSE.exe
echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Restarting WMI Service...
net start winmgmt
echo Done!
pause
